### PR TITLE
Release kubewarden 1.6.2

### PR DESCRIPTION
**Pull request by jordojordo**

### CODE REVIEW

**Review by aalves08 — APPROVED** [review]
LGTM

**Comment by kravciak** [comment]
PR did does not include `index.yaml` & `manifest.json` update.

**Comment by aalves08** [comment]
@kravciak you are totally right! I did not catch this 😱

FYI @jordojordo

**Comment by jordojordo** [comment]
Must have missed it in the rebase :man_facepalming: 

Corrected pr: https://github.com/rancher/ui-plugin-charts/pull/58

**Pull request merged**
